[package]
name = "server"
version = "0.1.0"
edition = "2021"
CARGO_INCREMENTAL = 1

[dependencies]
ntex = { version = "2", features = ["tokio"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
